http {
    #include /etc/nginx/mime.types;
    #default_type application/octet-stream;
    #sendfile on;
    #keepalive_timeout 65;

    upstream threadservice {
        server threadservice:5005; 
    }

    upstream postservice {
        server postservice:5001; 
    }

    server {
        listen 9999;
        server_name localhost;

        # Общие заголовки для прокси
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Корневой endpoint для информации
        #location / {
        #    return 200 "Welcome to Forum API Gateway\nAvailable endpoints:\n- /threads/\n- /posts/";
        #    add_header Content-Type text/plain;
        #}

        location /threads/ {
            proxy_pass http://threadservice/;
        }

        location /posts/ {
            proxy_pass http://postservice/;
        }
    }
}

events {
    #worker_connections 1024;
}